version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/cook_me_gpt
    command: python manage.py runserver 0.0.0.0:8000