# Generated by Django 4.2.1 on 2023-06-01 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_recipe_date_created_alter_recipe_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 10, 49, 34, 113783)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
