# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

on:
  workflow_call:
    inputs:
      deployment-environment:
        required: true
        type: string
      version:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  get-environment:
    name: Get Environment
    uses: Gershon-A/cookme/.github/workflows/environment.yaml@main

  generate-version:
    name: Generate Version
    needs: get-environment
    if: needs.get-environment.outputs.deployment-environment != ''
    uses: Gershon-A/cookme/.github/workflows/version.yaml@main
    with:
      deployment-environment: ${{ needs.get-environment.outputs.deployment-environment }}

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [get-environment, generate-version]
    permissions:
      contents: read
      packages: write

    env:
      DEPLOYMENT_ENVIRONMENT: ${{ needs.get-environment.outputs.deployment-environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.COOKME_GITHUB_WORKFLOW_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
